version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: kombu
    versions:
    - ">= 5.a, < 6"
  - dependency-name: playwright
    versions:
    - 0.171.1
    - 1.9.0
  - dependency-name: pytest-playwright
    versions:
    - 0.0.10
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
