# -*- coding: utf-8 -*-
# Generated by Django 3.1.3 on 2020-11-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="picture",
            field=models.ImageField(
                default="testing.jpeg", upload_to="thumbnail", verbose_name="Picture"
            ),
        ),
    ]
