# -*- coding: utf-8 -*-
# Generated by Django 3.1.3 on 2020-11-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile", verbose_name="Picture"
            ),
        ),
    ]
